CREATE PROC  clearAllTables
AS
TRUNCATE TABLE Employee_Approve_Leave
TRUNCATE TABLE Employee_Replace_Employee
TRUNCATE TABLE Performance
TRUNCATE TABLE Deduction
TRUNCATE TABLE Attendance
TRUNCATE TABLE Payroll
TRUNCATE TABLE Document
TRUNCATE TABLE Compensation_Leave
TRUNCATE TABLE Unpaid_Leave
TRUNCATE TABLE Medical_Leave
TRUNCATE TABLE Accidental_Leave
TRUNCATE TABLE Annual_Leave
TRUNCATE TABLE Medical_Leave
TRUNCATE TABLE Leave
TRUNCATE TABLE Role_existsIn_Department
TRUNCATE TABLE Employee_Role
TRUNCATE TABLE Role
TRUNCATE TABLE Employee_Phone
TRUNCATE TABLE Employee
TRUNCATE TABLE Department
GO